name: Release TDX components
on: [create, workflow_dispatch]

env:
  RUST_TOOLCHAIN: nightly-2023-12-31
  TOOLCHAIN_PROFILE: minimal
  TD_SHIM_CODE_REV: 7b7a87388a20a525126b5b9b95a003921b0c90e1
  KATA_CODE_REV: 1ad87faaf

jobs:
  release:
    if: github.event_name == 'create' && github.event.ref_type== 'tag'
    name: Release
    runs-on: ubuntu-20.04

    steps:
      - name: install NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rust-src

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo install cargo-xbuild
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-xbuild

      - name: Generate td-shim/guest-image/kernel and reference values
        run: |
          cd scripts/tdx && make release

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "scripts/tdx/destdir/*"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          artifacts: "scripts/tdx/destdir/*"
          allowUpdates: true
